# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: chatgpt-backend-fastapi
metadata:
  template: chatgpt-backend-fastapi@0.0.1-beta
services:
  aca:
    docker:
      remoteBuild: true
    project: ./src
    language: py
    host: containerapp
pipeline:
  variables:
    - AZURE_OPENAI_RESOURCE
    - AZURE_OPENAI_RESOURCE_LOCATION
    - AZURE_OPENAI_RESOURCE_GROUP
    - AZURE_OPENAI_SKU_NAME
    - ALLOWED_ORIGINS
